### ISSUE TITLE
[PHP formatter] blank lines

### ISSUE THREAD

**Issue by thewholelifetolearn** [pulse00/Symfony-2-Eclipse-Plugin#149]
There is nothing written in PSR standards but if we take the [following example](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#45-abstract-final-and-static), I think we should change the values for "Before class declarations" and "Before function declarations" to 1 instead of 0

**Comment by zulus** [comment]
I think that current psr-2 standard, built-in PDT is ok.
