### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by super-ienien** [pulse00/Symfony-2-Eclipse-Plugin#153]
hi i can't install your plugin on Eclipse PDT 3.0.2 using this repository : http://p2.dubture.com

here is the error report 

Unable to read repository at http://www.twig-project.org/.
http://www.twig-project.org/ is not a valid repository location.
Unable to read repository at http://pear.php.net/package/PHP_CodeSniffer.
http://pear.php.net/package/PHP_CodeSniffer is not a valid repository location.
No repository found at http://symfony.dubture.com.
No repository found at http://getcomposer.org/.

**Comment by zulus** [comment]
Plugin require PDT 3.5 since last version and installing work correctly. Closing.
