### ISSUE TITLE
Set project facet

### ISSUE THREAD

**Issue by althaus** [pulse00/Symfony-2-Eclipse-Plugin#166]
Hey,

I added an existing project based on 2.3-dev-something to Eclipse. Adding a new Symfony project through Eclipse allows to choose 2.3.x. Setting the project facet for my existing one is limited to choose between 2.1 and 2.2.

Something wrong or did I missunderstood this?

Cheers
Matthias

PS: Thanks for this plugin full of awesomesauce! <3

**Comment by zulus** [comment]
Closing based on last comment. Please reopen if it happen again.
