### ISSUE TITLE
Host Proxy settings not picked up

### ISSUE THREAD

**Issue by richard-scott** [pulse00/Symfony-2-Eclipse-Plugin#178]
When your OS (Windows 7) has Proxy setup for IE, the settings are picked up by Eclipse in Preferences -> General -> Network Connections but the plugin doesn't use these and things like the "Symfony Version" dropdown box don't populate.

**Comment by XMBomb** [comment]
Hi,
I'm also having problems with proxies and this plugin (also using Windows 7)
If the Symfony Version Combox isn't populated it fails to create a project. Connecting directly to WAN fixes the problem. Is there a setting I've missed? I added all proxy settings to eclipse and eclipse does have access to the internet (I could download the plugin).

**Comment by zulus** [comment]
See also: pulse00/Composer-Eclipse-Plugin#79

**Comment by zulus** [comment]
Fixed by pulse00/Composer-Java-Bindings#18
