### ISSUE TITLE
[PHP formatter] Adding unnecessary whitespaces

### ISSUE THREAD

**Issue by shochdoerfer** [pulse00/Symfony-2-Eclipse-Plugin#181]
When using the built-in PSR-2 code formatter I get a whitespaces appended to all my @param lines in my docblock comments. Is there any way to get rid of those? I let php-cs-fixer reformat all my source files and wanted to check how much the built in PSR-2 code formatter differs and realised that almost all of my source files changed again because the code formatter was adding whitespaces all over the place.

After running the source formatter this docblock comment:
```php
    /**
     * Sets the value of $host.
     *
     * @param string $host
     */
```
turned into his docblock comment:
```php
    /**
     * Sets the value of $host.
     *
     * @param string $host            
     */
```

**Comment by zulus** [comment]
Formatter is not part of this plugin. You should report issue on PDT bugzilla.

If problem still exists, workaround may be disable PHPDoc formatting.
