### ISSUE TITLE
No php executable found

### ISSUE THREAD

**Issue by psyray** [pulse00/Symfony-2-Eclipse-Plugin#186]
Hi,

At project creation i have this error :
"No PHP executable defined. Please specify a valid executable in the PHP Executables preference page."
![symfony-eclipse-bug-1](https://f.cloud.github.com/assets/1230954/1716373/0571fb4a-61c0-11e3-9b40-43769d8f3fc9.jpg)

But I have an executable php defined in the right section (pref->php->php executable).
![symfony-eclipse-bug-2](https://f.cloud.github.com/assets/1230954/1716377/110959d0-61c0-11e3-95c0-588e6d9316f9.jpg)

I use xdebug to debug other project (no symfony project) and it works well.

So what's the problem ?
Am i doing something wrong ?

I try to find with google if there is a solution, but none....
So i open this issue.

My config is :
- Eclipse Kepler SR1 (Build id: 20130919-0819)
- Open JDK 7 (7u25-2.3.12)
- Xampp 1.8.3 (PHP 5.5.6), 
- Linux Mint 16

Thanks for help
Raynald

**Comment by shakaran** [comment]
Same behaviour than @elcapo using "Search" with /usr/bin in Ubuntu 15.04 with Eclipse 4.4 and PHP 5.6.4.

Please reopen the issue. The plugin is unusable if you don't know this "search" trick. I came here searching via google through this StackOverflow question http://stackoverflow.com/questions/26061626/no-php-executable-defined-eclipse-symfony

**Comment by zulus** [comment]
I have to investigate

**Comment by zulus** [comment]
This is PDT bug, and was fixed couple releases ago.
