### ISSUE TITLE
Project Clean - Build Path issue

### ISSUE THREAD

**Issue by bksunday** [pulse00/Symfony-2-Eclipse-Plugin#206]
Hi,

I've been using this plugin for over a year now I think and it's been really great!

But I am having an issue that may be my misunderstanding of how it should go, or a bad habit of mine. But since I haven't solved it since so long, I'm hoping someone could shed some light here.

Basically, I have some services and test classes that I pass the symfony Kernel. But whenever code assist is implied with AppKernel, I always end up with "The type \AppKernel cannot be resolved or namespace is empty" after a Project->Clean..., until I re-add the app/ folder to the Build Path.

It seems like Project->Clean resets the Build path to some default that adds src/ folder and each vendor/[vendor] folder.

Is there anyway I could prevent Project->Clean from resetting the build path? Or is that normal? I would rather have my build path with app/ src/ and vendor/ (with vendor exclusions like the default ones you provide, but not an entry for each vendor)

Thanks.

**Comment by zulus** [comment]
Composer plugin is now part of PDT.
