### ISSUE TITLE
Download installed package

### ISSUE THREAD

**Issue by Rvanlaak** [pulse00/Symfony-2-Eclipse-Plugin#209]
It is possible to download the latest Luna release including the PDT packages.
http://eclipse.org/pdt/#download

Because of many installation errors, it would be nice to be able to download a pre-installed package with all Symfony2 features working.

I've been busy half a day to get code completion working, but it still does not work. Every new Eclipse release I have this problem, so this would solve that for many (new) users.

**Comment by zulus** [comment]
Main problem was fixed after p2-dev restructure.

We now provide repo for stable pdt (p2.pdt-extensions.org) - it's connected to marketplace and latest stable PDT. And also p2-dev.pdt-extensions.org in sync with pdt nighties.

After release I'm testing on fresh eclipse for php developers.

Closing. Please reopen if you not agree.
