### ISSUE TITLE
error parsing namespace parts for {PHP core class}

### ISSUE THREAD

**Issue by thkoch2001** [pulse00/Symfony-2-Eclipse-Plugin#210]
The use line in

``` php
namespace PhpOption;

use IteratorAggregate;
```

from
https://github.com/schmittjoh/php-option/blob/master/src/PhpOption/Option.php#L21

causes a "error parsing namespace parts for IteratorAggregate".

Symfony Feature version: 1.0.95.201406201738

composer.lock for the dependency:

"name": "phpoption/phpoption",
            "version": "1.4.0",
            "source": {
                "type": "git",
                "url": "https://github.com/schmittjoh/php-option.git",
                "reference": "5d099bcf0393908bf4ad69cc47dafb785d51f7f5"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/schmittjoh/php-option/zipball/5d099bcf0393908bf4ad69cc47dafb785d51f7f5",
                "reference": "5d099bcf0393908bf4ad69cc47dafb785d51f7f5",
                "shasum": ""
            },

copy of the warning:

eclipse.buildId=4.4.0.I20140606-1215
java.version=1.7.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product org.eclipse.platform
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.php.product org.eclipse.platform

com.dubture.symfony.core
Warning
Mon Aug 18 13:17:13 CEST 2014
/myproject/vendor/phpoption/phpoption/src/PhpOption/Option.php: error parsing namespace parts for IteratorAggregate

**Comment by echosa** [comment]
It seems this is still an issue. I decided to try Eclipse with this plugin today. I get this same error in my log, many times of course. I'm not sure if this is due to parsing specifically imports of PHP core classes or any import that doesn't have a hierarchy (no backslash). Examples of statements that cause this error: `use Exception`, `use ArrayObject`, `use Memcached`.
