### ISSUE TITLE
Dependencies for default Symfony project can't be installed

### ISSUE THREAD

**Issue by mniewrzal** [pulse00/Symfony-2-Eclipse-Plugin#220]
Dependency installation (Composer part) after Symfony project creation fails with given output:

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for symfony/symfony 3.0.x-dev -> satisfiable by symfony/symfony[3.0.x-dev].
    - doctrine/doctrine-bundle v1.2.0 requires symfony/doctrine-bridge ~2.2 -> satisfiable by symfony/symfony[2.2.x-dev, 2.3.x-dev, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, 2.7.x-dev], symfony/doctrine-bridge[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.1
8, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.3, v2.3.4, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6].
    - Can only install one of: symfony/symfony[3.0.x-dev, 2.2.x-dev].
    - Can only install one of: symfony/symfony[3.0.x-dev, 2.3.x-dev].
    - Can only install one of: symfony/symfony[3.0.x-dev, 2.4.x-dev].
    - Can only install one of: symfony/symfony[3.0.x-dev, 
2.5.x-dev].
    - Can only install one of: symfony/symfony[3.0.x-dev, 2.6.x-dev].
    - Can only install one of: symfony/symfony[3.0.x-dev, 2.7.x-dev].
    - don't install symfony/doctrine-bridge v2.2.0|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.1|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.10|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.11|don't install symfony/symfon
y 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.2|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.3|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.4|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.5|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.6|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-br
idge v2.2.7|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.8|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.2.9|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.0|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.1|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.10|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.11|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.12|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.13|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.14|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.15|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v
2.3.16|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.17|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.18|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.19|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.2|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.20|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.21|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.3|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.4|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.5|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.6|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.7
|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.8|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.3.9|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.0|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.1|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.10|don't install symfony/symfony 3.0.x-dev
    - don
't install symfony/doctrine-bridge v2.4.2|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.3|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.4|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.5|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.6|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.7|don't inst
all symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.8|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.4.9|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.0|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.1|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.2|don't install symfony/symfony 3.0.x-dev
    - don't install s
ymfony/doctrine-bridge v2.5.3|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.4|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.5|don't install symfony/symfony 3.0.x-dev
    - don't install symfony/doctrine-bridge v2.5.6|don't install symfony/symfony 3.0.x-dev
    - Installation request for doctrine/doctrine-bundle ~1.2 -> satisfiable by doctrine/doctrine-bundle[v1.2.0].

![screenshot from 2014-11-17 14 54 10](https://cloud.githubusercontent.com/assets/7313031/5070678/c99c2a5c-6e69-11e4-8585-cff0a6fb9a1b.png)

I'm not sure if it is Symfony plugin fault but it can be frustrating for new users.

**Comment by zulus** [comment]
Looks like this was composer problem. Now everything working correctly. Closing.
