### ISSUE TITLE
The symfony create project wizard gives error

### ISSUE THREAD

**Issue by ruizito** [pulse00/Symfony-2-Eclipse-Plugin#223]
Hi there! I have a windows7 system with xampp working
I made a fresh install of:
1) Eclipse Kepler
2) plugins in http://p2-dev.pdt-extensions.org/

On creating a new symfony project I get a long error log.
Can someone point me out how to solve this? I attach Eclipse's log file:

!SESSION 2015-01-15 01:13:23.965 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_PT
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.jface 2 0 2015-01-15 01:13:35.837
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:13:35.837
!MESSAGE A conflict occurred for CTRL+G:
Binding(CTRL+G,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace,Declaration in Workspace,
		Search for declarations of the selected element in the workspace,
		Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3e4e4c1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+G,
	ParameterizedCommand(Command(org.pdtextensions.core.ui.generategetters,Generate Getters and Setters,
		Generate Getters and Setters,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7e7f3cfd,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:13:35.837
!MESSAGE A conflict occurred for ALT+SHIFT+X Q:
Binding(ALT+SHIFT+X Q,
	ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.run,Run Ant Build,
		Run Ant Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3ae126d1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+X Q,
	ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.run,Run Phing Build,
		Run Phing Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@46a488c2,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:13:35.837
!MESSAGE A conflict occurred for ALT+SHIFT+D Q:
Binding(ALT+SHIFT+D Q,
	ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.debug,Debug Ant Build,
		Debug Ant Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6242ae3b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+D Q,
	ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.debug,Debug Phing Build,
		Debug Phing Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@65ddee5a,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.ui 4 4 2015-01-15 01:13:41.658
!MESSAGE Conflicting handlers for org.eclipse.ant.ui.antShortcut.run: {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@510a2c7} vs {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@14fe085b}

!ENTRY org.eclipse.ui 4 4 2015-01-15 01:13:41.658
!MESSAGE Conflicting handlers for org.eclipse.ant.ui.antShortcut.debug: {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@2ae88712} vs {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@10508ba6}

!ENTRY org.eclipse.osgi 2 1 2015-01-15 01:16:36.650
!MESSAGE NLS unused message: PathMapperCompositeFragment_5 in: org.eclipse.php.internal.server.ui.messages
!SESSION 2015-01-15 01:19:56.929 -----------------------------------------------
eclipse.buildId=4.3.2.M20140221-1700
java.version=1.8.0_25
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=pt_PT
Framework arguments:  -product org.eclipse.epp.package.standard.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.standard.product

!ENTRY org.eclipse.jface 2 0 2015-01-15 01:20:03.175
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:20:03.175
!MESSAGE A conflict occurred for CTRL+G:
Binding(CTRL+G,
	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.search.declarations.in.workspace,Declaration in Workspace,
		Search for declarations of the selected element in the workspace,
		Category(org.eclipse.search.ui.category.search,Search,Search command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@4aa11206,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(CTRL+G,
	ParameterizedCommand(Command(org.pdtextensions.core.ui.generategetters,Generate Getters and Setters,
		Generate Getters and Setters,
		Category(org.eclipse.ui.category.edit,Edit,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@40d60f2,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:20:03.175
!MESSAGE A conflict occurred for ALT+SHIFT+X Q:
Binding(ALT+SHIFT+X Q,
	ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.run,Run Ant Build,
		Run Ant Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@3382cf68,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+X Q,
	ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.run,Run Phing Build,
		Run Phing Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2f74900b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
!SUBENTRY 1 org.eclipse.jface 2 0 2015-01-15 01:20:03.175
!MESSAGE A conflict occurred for ALT+SHIFT+D Q:
Binding(ALT+SHIFT+D Q,
	ParameterizedCommand(Command(org.eclipse.ant.ui.antShortcut.debug,Debug Ant Build,
		Debug Ant Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@6d8796c1,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)
Binding(ALT+SHIFT+D Q,
	ParameterizedCommand(Command(org.ganoro.phing.ui.antShortcut.debug,Debug Phing Build,
		Debug Phing Build,
		Category(org.eclipse.debug.ui.category.run,Run/Debug,Run/Debug command category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@2e26173,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.contexts.window,,,system)

!ENTRY org.eclipse.ui 4 4 2015-01-15 01:20:08.121
!MESSAGE Conflicting handlers for org.eclipse.ant.ui.antShortcut.run: {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@348bd063} vs {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@3d73cd78}

!ENTRY org.eclipse.ui 4 4 2015-01-15 01:20:08.121
!MESSAGE Conflicting handlers for org.eclipse.ant.ui.antShortcut.debug: {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@53a16dd6} vs {org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension$LaunchCommandHandler@126d8659}

!ENTRY org.eclipse.egit.ui 2 0 2015-01-15 01:21:43.176
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\Rui Almeida'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.core.contenttype 4 0 2015-01-15 01:21:43.878
!MESSAGE Could not create content describer for org.ganoro.phing.core.antBuildFile. Content type has been disabled.

!ENTRY org.eclipse.core.resources 4 2 2015-01-15 01:21:46.109
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceParserFactory.parse([C[CLorg/eclipse/dltk/compiler/problem/IProblemReporter;)Lorg/eclipse/dltk/ast/declarations/ModuleDeclaration;
	at org.phpaspect.apdt.internal.core.builder.AnnotationBuildParticipant.build(AnnotationBuildParticipant.java:18)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildModule(StandardScriptBuilder.java:242)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildNatureModules(StandardScriptBuilder.java:176)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.build(StandardScriptBuilder.java:73)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.fullBuild(ScriptBuilder.java:448)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.build(ScriptBuilder.java:156)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.core.resources 4 75 2015-01-15 01:21:46.140
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.dltk.core 4 75 2015-01-15 01:21:46.140
!MESSAGE Errors running builder 'Script Builder' on project 'testy'.
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceParserFactory.parse([C[CLorg/eclipse/dltk/compiler/problem/IProblemReporter;)Lorg/eclipse/dltk/ast/declarations/ModuleDeclaration;
	at org.phpaspect.apdt.internal.core.builder.AnnotationBuildParticipant.build(AnnotationBuildParticipant.java:18)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildModule(StandardScriptBuilder.java:242)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildNatureModules(StandardScriptBuilder.java:176)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.build(StandardScriptBuilder.java:73)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.fullBuild(ScriptBuilder.java:448)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.build(ScriptBuilder.java:156)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.340
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.340
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.356
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.356
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.356
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.356
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.372
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.372
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.372
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.372
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.372
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.387
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.387
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.387
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.387
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.403
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.403
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.403
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.403
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.902
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.902
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.902
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.918
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.918
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.918
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.933
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.933
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.933
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.949
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.949
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.949
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.949
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.949
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.964
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.964
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.964
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.964
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:16.964
!MESSAGE Unable to parse class attribute from service [service: null]

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:17.686
!MESSAGE Error setting marker for synthetic service service_container

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:17.686
!MESSAGE Error setting marker for synthetic service kernel

!ENTRY com.dubture.symfony.core 1 1 2015-01-15 01:25:17.749
!MESSAGE Error setting marker for synthetic service request

!ENTRY org.eclipse.core.resources 4 2 2015-01-15 01:25:17.983
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.core.resources".
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceParserFactory.parse([C[CLorg/eclipse/dltk/compiler/problem/IProblemReporter;)Lorg/eclipse/dltk/ast/declarations/ModuleDeclaration;
	at org.phpaspect.apdt.internal.core.builder.AnnotationBuildParticipant.build(AnnotationBuildParticipant.java:18)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildModule(StandardScriptBuilder.java:242)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildNatureModules(StandardScriptBuilder.java:176)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.build(StandardScriptBuilder.java:73)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.fullBuild(ScriptBuilder.java:448)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.build(ScriptBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY org.eclipse.core.resources 4 75 2015-01-15 01:25:17.998
!MESSAGE Errors occurred during the build.
!SUBENTRY 1 org.eclipse.dltk.core 4 75 2015-01-15 01:25:17.998
!MESSAGE Errors running builder 'Script Builder' on project 'testy'.
!STACK 0
java.lang.NoSuchMethodError: org.eclipse.php.internal.core.compiler.ast.parser.PHPSourceParserFactory.parse([C[CLorg/eclipse/dltk/compiler/problem/IProblemReporter;)Lorg/eclipse/dltk/ast/declarations/ModuleDeclaration;
	at org.phpaspect.apdt.internal.core.builder.AnnotationBuildParticipant.build(AnnotationBuildParticipant.java:18)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildModule(StandardScriptBuilder.java:242)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.buildNatureModules(StandardScriptBuilder.java:176)
	at org.eclipse.dltk.internal.core.builder.StandardScriptBuilder.build(StandardScriptBuilder.java:73)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.fullBuild(ScriptBuilder.java:448)
	at org.eclipse.dltk.internal.core.builder.ScriptBuilder.build(ScriptBuilder.java:171)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:733)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.385
!MESSAGE /testy/vendor/doctrine/common/lib/Doctrine/Common/Reflection/RuntimePublicReflectionProperty.php: error parsing namespace parts for ReflectionProperty

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.385
!MESSAGE /testy/vendor/doctrine/common/lib/Doctrine/Common/Reflection/StaticReflectionClass.php: error parsing namespace parts for ReflectionClass

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.401
!MESSAGE /testy/vendor/doctrine/common/lib/Doctrine/Common/Reflection/StaticReflectionMethod.php: error parsing namespace parts for ReflectionMethod

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.432
!MESSAGE /testy/vendor/doctrine/common/lib/Doctrine/Common/Reflection/StaticReflectionProperty.php: error parsing namespace parts for ReflectionProperty

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.760
!MESSAGE /testy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/OCI8/OCI8Statement.php: error parsing namespace parts for IteratorAggregate

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.775
!MESSAGE /testy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php: error parsing namespace parts for PDO

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.869
!MESSAGE /testy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/SQLAnywhere/SQLAnywhereStatement.php: error parsing namespace parts for IteratorAggregate

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:20.900
!MESSAGE /testy/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/SQLSrv/SQLSrvStatement.php: error parsing namespace parts for IteratorAggregate

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:23.572
!MESSAGE /testy/vendor/doctrine/orm/lib/Doctrine/ORM/Id/SequenceGenerator.php: error parsing namespace parts for Serializable

!ENTRY com.dubture.symfony.core 2 2 2015-01-15 01:25:24.102
!MESSAGE /testy/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php: error parsing namespace parts for Exception

**Comment by zulus** [comment]
What PDT and DLTK version you have? You can check this in "About Eclipse" window

**Comment by ruizito** [comment]
Hi @zulus, I think these plugins came in http://p2-dev.pdt-extensions.org/, among other I have therefore:
I have, among others, the following plugins:
  PHP Development Tools (PDT)	3.4.0.201501141153	org.eclipse.php.feature.group	Eclipse.org
    (Dynamic Languages Toolkit - Core Frameworks	5.1.1.201501140007	org.eclipse.dltk.core.feature.group	Eclipse.org
    Dynamic Languages Toolkit - Core H2 Index Frameworks	5.1.1.201501140007	org.eclipse.dltk.core.index.feature.group	Eclipse.org
  PHP Development Tools (PDT) JUnit Tests	3.4.0.201501141153	org.eclipse.php.test.feature.group	Eclipse.org)
  PHP Development Tools (PDT) Mylyn Integration	3.4.0.201501141153	org.eclipse.php.mylyn.feature.group	Eclipse.org
    (Dynamic Languages Toolkit - Mylyn Integration	5.1.1.201501140007	org.eclipse.dltk.mylyn.feature.group	Eclipse.org)
  PHP Development Tools (PDT) Source Code	3.4.0.201501141153	org.eclipse.php.source.feature.group	Eclipse.org

**Comment by zulus** [comment]
APDT is not compatible with this PDT version. You should uninstall it.

**Comment by ruizito** [comment]
Ok, thank you for that ... the directory structure is now created without error!
The workspace build did take a long time...
Now I'm not (yet) very knowledgable in symfony but on this projecct creation two errors are reported:
Description	Resource	Path	Location	Type
cvc-complex-type.2.4.a: Invalid content was found starting with element 'factory'. One of '{"http://symfony.com/schema/dic/services":file, "http://symfony.com/schema/dic/services":argument, "http://symfony.com/schema/dic/services":configurator, "http://symfony.com/schema/dic/services":call, "http://symfony.com/schema/dic/services":tag, "http://symfony.com/schema/dic/services":property}' is expected.	appDevDebugProjectContainer.xml	/teste5/app/cache/dev	line 1326	XML Problem
cvc-complex-type.2.4.a: Invalid content was found starting with element 'factory'. One of '{"http://symfony.com/schema/dic/services":file, "http://symfony.com/schema/dic/services":argument, "http://symfony.com/schema/dic/services":configurator, "http://symfony.com/schema/dic/services":call, "http://symfony.com/schema/dic/services":tag, "http://symfony.com/schema/dic/services":property}' is expected.	appDevDebugProjectContainer.xml	/teste5/app/cache/dev	line 1367	XML Problem

How do I solve this?

**Comment by ruizito** [comment]
Hi @zulus, also, going into my local web server http://localhost/teste5/web/, I get displayed a series of errors related to:
"Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'symfony'' in C:\xampp\htdocs\teste5\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 103"

Also I have no permission to go into http://localhost/teste5/app/

Any help?

**Comment by zulus** [comment]
For first, looks like WTP is traying to validate cache xml files. you should disable it now manualy. RPM on project -> validation. Enable project specific settings, next add app/cache to filters on xml schema validator.

For second question, you haven't database created. Please read a symfony manual: http://symfony.com/doc/current/index.html

**Comment by ruizito** [comment]
Hi, in the mean time I uninstalled everything I remember having installed in relation to the setup of symfony on Eclipse... And installed Eclipse again with just the symfony plugin...
I have an error that I got around last time by installing git (http://msysgit.github.io/) since it was not found(though Eclipse has Egit). Is it safe to say that this plugin needs, besides Eclipse 4.3, Java 6, also Git?

**Comment by zulus** [comment]
Eclipse have egit, but symfony plugin use composer plugin while installing. Composer plugin just run composer.phar cmd_name, and because many packagist vendors are download directly from github repo, yes Symfony Plugin indirectly require installed git in system.

**Comment by ruizito** [comment]
Ok, now everything is working!
Had to follow your indications regarding the validation of xml files.
Thank you @zulus!
