### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by brodao** [pulse00/Symfony-2-Eclipse-Plugin#227]
My plugin depends on org.pdtextensions.core resources.
I use maven to build my plugins and this plugin the error occurs:
[ERROR] Can not resolve project dependencies:
[ERROR] Software being installed: br.com.acandido.symfony 1.5.0.qualifier
[ERROR] Missing requirement: br.com.acandido.symfony 1.5.0.qualifier requires 'bundle org.pdtextensions.core 0.0.0' but it could not be found
[ERROR]

You know what the definition tells Maven repository should I use?

thank you,

PS: Sorry my english.

**Comment by zulus** [comment]
You can add this repository:

```xml
<repository>
  <id>pex</id>
  <layout>p2</layout>
  <url>http://p2-dev.pdt-extensions.org/</url>
</repository>
```

**Comment by brodao** [comment]
Zulus,

Thanks, but is not work. In log only my others repository "added".

[INFO] Computing target platform for MavenProject: br.com.acandido.symfony:br.com.acandido.symfony:1.5.0-SNAPSHOT @ W:\acTools\br.com.acandido.symfony\pom.xml
[DEBUG] Added p2 repository luna (http://download.eclipse.org/releases/luna)
[DEBUG] Added p2 repository papyrus (http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna)
[DEBUG] Added p2 repository papyrus-extra (http://download.eclipse.org/modeling/mdt/papyrus/updates/releases/luna/extra)
[DEBUG] Added p2 repository babel (http://download.eclipse.org/technology/babel/update-site/R0.12.1/luna)
[DEBUG] Added p2 repository swtbot (http://download.eclipse.org/technology/swtbot/releases/latest)
[DEBUG] Using execution environment 'JavaSE-1.7' configured in Bundle-RequiredExecutionEnvironment

Any idea?

**Comment by zulus** [comment]
Can you upload somewhere (gist) your pom.xml file? Or it's <repositories> section?

**Comment by brodao** [comment]
Thanks for all,

I delete my local repository and working now.
