### ISSUE TITLE
Is Zend Studio supported by this feature?

### ISSUE THREAD

**Issue by parhamdoustdar** [pulse00/Symfony-2-Eclipse-Plugin#228]
This feature doesn't work on my Zend Studio 12.0.2 running on a Windows PC. I was wondering if Zend Studio is supported, or if you only support the Eclipse PDT?

**Comment by zulus** [comment]
In theory should work. Zend Studio since 12.0 is based on e4 platform.

Besides, as far as I know Zend Studio have builtin ability to install these plugins.

**Comment by parhamdoustdar** [comment]
Well, when I installed it, my Zend Studio kept crashing. I'm a bit scared to install it again (I had to reinstall and reconfigure my Zend Studio), so that's why I asked. I will install it again and paste the log.

**Comment by zulus** [comment]
I fixed some depenency probles with latest eclipse. Should also fix your problems. Closing for now.
