### ISSUE TITLE
I get error on installation

### ISSUE THREAD

**Issue by Superdrac** [pulse00/Symfony-2-Eclipse-Plugin#230]
Hi, when i try to install it via eclipse (with this url:  http://p2-dev.pdt-extensions.org/ ), it just crash and i get this error: 

> An error occurred while collecting items to be installed
session context was:(profile=SDKProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.dubture.doctrine.annotation,1.0.8.201505050853
No repository found containing: osgi.bundle,com.dubture.doctrine.core,1.0.8.201505050853
No repository found containing: org.eclipse.update.feature,com.dubture.doctrine.feature,1.0.8.201505050853
No repository found containing: osgi.bundle,com.dubture.doctrine.ui,1.0.8.201505050853
No repository found containing: osgi.bundle,com.dubture.indexing.core,0.0.15.201406101349
No repository found containing: osgi.bundle,com.dubture.symfony.core,1.1.0.201505050858
No repository found containing: osgi.bundle,com.dubture.symfony.debug,1.1.0.201505050858
No repository found containing: org.eclipse.update.feature,com.dubture.symfony.feature,1.1.0.201505050858
No repository found containing: osgi.bundle,com.dubture.symfony.index,1.1.0.201505050858
No repository found containing: osgi.bundle,com.dubture.symfony.twig,1.1.0.201505050858
No repository found containing: osgi.bundle,com.dubture.symfony.ui,1.1.0.201505050858

Is there a way to correct it ?

Thank !

**Comment by zulus** [comment]
Looks like broken p2 cache. 
Go to preferences -> available software sites. Next select pex repository and click "reload"

**Comment by Superdrac** [comment]
I just tried it and it don't work better, I get exactly the same error.

**Comment by zulus** [comment]
Can you select "contact all update sites during install to find required software"? 

Or use direct link? : http://dl.bintray.com/pulse00/pdt-extensions/nightly/0.0.3/

**Comment by Superdrac** [comment]
"contact all update sites during install to find required software" is checked by default. 

I just tried with your link but i get the same error.

**Comment by zulus** [comment]
So can you also try with disabled ? This sometimes helps ;)

**Comment by Superdrac** [comment]
It worked ! I had to reload all my urls, i retried with your and it worked ! 

Thanks ! :smile:

**Comment by zulus** [comment]
No problem
