### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by zenus** [pulse00/Symfony-2-Eclipse-Plugin#231]
hi, you really did a nice work , and i want write  a plugin for  another  php framework , so i think i can get some information from your code ,and i use the projectSet.psf to get your code  , but  i get a problem, all as the picture said 
![image](https://cloud.githubusercontent.com/assets/10082589/8147612/e2f15f68-12a6-11e5-96d4-7f23bc09c46c.png)

**Comment by zulus** [comment]
I'm don't know why your eclipse don't like  PSF files, but you can easy import exising project, via file -> import -> existing project into workspace

**Comment by zenus** [comment]
i really know little about developing a plug for php framework in eclipse , do you have some blogs or articles to recommend ?

**Comment by zulus** [comment]
* Off course vogella (http://vogella.com/) for general RCP plugin develop.
* Guide for DLTK : http://wiki.eclipse.org/A_guide_to_building_a_DLTK-based_language_IDE
* Small presentation howto extend PDT : http://www.slideshare.net/wcandillon/extending-and-scripting-pdt
* PDT developer resources : https://wiki.eclipse.org/PDT#Developer_Resources
* PDT-dev mailing list if you need help : https://dev.eclipse.org/mailman/listinfo/pdt-dev

**Comment by zulus** [comment]
Closing, please reopen if you need more information
