### ISSUE TITLE
Exclusion of folders is overwritten

### ISSUE THREAD

**Issue by nea** [pulse00/Symfony-2-Eclipse-Plugin#236]
Hi

I have the current issue with the newest Eclipse Version: Mars Release (4.5.0) and  Symfony Feature 1.1.1.201507280704 that no matter if I exclude the app/ folder from the build path it will be readded after some time. I do not really know when, but sometimes after a refresh, a search for a class or even save it gets readded. I excluded it especially because of the cache/ folder, which should not be indexed and as I don't want to have the Doctrine Proxy classes in the Class Selection in Eclipse.

Is there a way to exclude a folder permantely or at least exclude the cache/ folder as I don't see a necessity in it.

Thanks
 Savas

**Comment by koddistortion** [comment]
+1

**Comment by Viburnum** [comment]
+1

**Comment by zulus** [comment]
Composer refresh buildpath after each update by default. You can disable it in Composer->Save Action. My solution (workaround) for pernament fix:

1. Select app/cache dir -> right mouse -> properties
2. In properties window go to Resources -> Resources Window add filter
3. exclusive / files / recursive / *.php
4. Save / apply and viola

**Comment by nea** [comment]
Zulus... my deepest appreciation for that hint. Thanks a lot :)

**Comment by bysouleater** [comment]
Thank @zulus very much! I had to also add *.xml as another filter

**Comment by zulus** [comment]
Composer plugin is now part of PDT
