### ISSUE TITLE
Doctrine Feature doesn't accept PHP 7 scalar types

### ISSUE THREAD

**Issue by advancingu** [pulse00/Symfony-2-Eclipse-Plugin#243]
When "Doctrine Feature" is installed, the new PHP 7 type hinting for scalar types gets flagged as a warning regarding a missing `use` statement.
Example:
```
<?php
class Foo
{
    public function testMe(string $bar)
    {
    }
}
```
In this example, `string` is highlighted as a warning.

I would expect the feature to correctly accept valid PHP 7 type hints.

**Comment by zulus** [comment]
This is Core-Plugin bug, see pdt-eg/Core-Plugin#128

**Comment by advancingu** [comment]
How come that when I uninstall "Doctrine Feature" the warning disappears?

**Comment by zulus** [comment]
Doctrine plugin have core-plugins installed as dependencies. Itself validate only annotation names.

Dependency pulse00/Symfony-2-Eclipse-Plugin => pulse00/Doctrine-Eclipse-Plugin => pdt-eg/Core-Plugin
