### ISSUE TITLE
Unused Import Warning for Annotations

### ISSUE THREAD

**Issue by jdwilliams19** [pulse00/Symfony-2-Eclipse-Plugin#244]
Versions:

Eclipse Neon 4.6.0.20160328-1000
Symfony Plugin 1.2.0.201603121155
PDT Plugin 4.0.0.201603241954

I'm not sure if this is a Symfony plugin bug or a PDT issue, but I have FOS rest-bundle installed via composer and when I add a @Route annotation, it auto-inserts the use statement, but it gets flagged with a warning: "Unused import 'FOS\RestBundle\Controller\Annotations\Route', consider removing." I can't use the "Organize Use Statements" feature now because it will remove the use statement and break the code.

**Comment by zulus** [comment]
This will be fixed in next neon build (M7), as far as I know will be released today.

See also: https://bugs.eclipse.org/bugs/show_bug.cgi?id=490434
