### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by brucegibbins** [pulse00/Symfony-2-Eclipse-Plugin#245]
Hello, I am new to PHP,Symfony and it has been a while since I worked in Eclipse. I am working on a PHP console cli based app (no web interface) but I have decided to still use the Symfony 3 framework along with PHP 7.x.

My problem is that I don't understand how to evoke the bin/console application an also enable step thru debugging. 

The plugin seems to be working with codeassist etc. I created my eclipse project by using the import symfony option.

Thank-You in advance

**Comment by zulus** [comment]
copy bin/console to bin/console.php (or create bin/console .php and add require bin/console). Next open debug configuration (smal sign aroung debug icon), add php cli configuration.

Select bin/console, correct php (if not default), and add script arguments, for example cache:clear ;)

**Comment by zulus** [comment]
See PDT help http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.php.help%2Fhtml%2Ftasks%2Fdebugging%2Flocally_debugging_a_php_script.html&cp=61_3_19_2

**Comment by brucegibbins** [comment]
Thanks Dawid

Thanks that makes sense and obvious when I think about it. I knew that bin/console was in fact a PHP file without the .php extension and had thought that maybe the authors of the plugin had catered for this.

The reason for this is that when you import an existing symfony project it builds a config that has bin/console already filled in so I had assumed that it was somehow aware that this was a PHP script and it would evoke it for me.

On the same topic I notice as I am on Windows and given my above statement - will this approach still work on Windows or is the plugin assuming a UNIX or Linux environment and assuming some type of shell aliasing would be in place and so not evoke PHP.exe?

Thanks again

Bruce

**Comment by brucegibbins** [comment]
Thanks very much Dawid. I was able to run my code within the symfony command context. Appreciate your assistance.

 

Cheers

**Comment by zulus** [comment]
I prepared bug on PDT for non php files: https://bugs.eclipse.org/bugs/show_bug.cgi?id=494529

closing for now
