### ISSUE TITLE
Mars:requires 'bundle org.eclipse.zest.core 0.0.0' but it could not be found 

### ISSUE THREAD

**Issue by linkivan** [pulse00/Symfony-2-Eclipse-Plugin#246]
My eclipse Version: Mars.1 Release (4.5.1). I tried to install the plugin from marketplace and both update sites but it all get same error:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Symfony Feature 1.2.0.201603121155 (com.dubture.symfony.feature.feature.group 1.2.0.201603121155)
  Missing requirement: Composer Eclipse UI Plugin 1.0.2.201507051455 (com.dubture.composer.ui 1.0.2.201507051455) requires 'bundle org.eclipse.zest.core 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Composer 1.0.2.201507051455 (com.dubture.composer.feature.feature.group 1.0.2.201507051455)
    To: com.dubture.composer.ui [1.0.2.201507051455]
  Cannot satisfy dependency:
    From: Symfony Feature 1.2.0.201603121155 (com.dubture.symfony.feature.feature.group 1.2.0.201603121155)
    To: com.dubture.composer.feature.feature.group 1.0.20.201603121155)
    To: com.dubture.composer.feature.feature.group 1.0.2

**Comment by zulus** [comment]
How tou install symfony plugin? Via market place or by install software? If second have tou cheched "contact all update site to resolve required software".

I checked neon and mars. Everything works correctly.
