### ISSUE TITLE
Install Breaks Eclipse

### ISSUE THREAD

**Issue by RangerGH** [pulse00/Symfony-2-Eclipse-Plugin#248]
I successfully installed the dubtree Twig plugin and restarted Eclipse.  I then installed the Symfony2 plugin successfully in that it asked to restart Eclipse.  I did and got "An error has occured.  See the log file..." (attached).  If i hit close to the error message Eclipse will not start.  I'll roll back to a snapshot I took of the machine before I installed this.

I'm running Fedora 24 and Eclipse Neon.

[log.txt](https://github.com/pulse00/Symfony-2-Eclipse-Plugin/files/416888/log.txt)

Edit:  The Twig plugin also causes the same behaviour.

**Comment by zulus** [comment]
Are you sure did you install only SF plugin? based on logs I see problem with CDT dependencies (cdt.cmake).

Also SVN plugin is unable to start (timeout).

**Comment by RangerGH** [comment]
I installed Eclipse from the Fedora Eclipse package and the pdt package both of which succeded.  I then installed YAML editor.

I went to the Marketplace from the Eclipse Help menu and installed the SF plugin from there which finished the install and asked for a restart which I did.  It then gave me the error and I had to roll back to a snapshot just before the install of SF plugin.  I researched the error and none of the suggested solutions such as remove cache directories worked.

As for CDT it got installed by default and I don't use it but since I got no errors on the install or startup after that I assumed all was well with it.

SVN I don't use since I use git. I assume it was installed as part of the package.

**Comment by RangerGH** [comment]
I did some more testing.  The install I'm having issues with was installed by installing the Fedora Eclipse package.  I cloned my Fedora 24 Workstation before Eclipse was installed and installed by downloading the PHP package (I was going to use the oomph installer but it isn't smart enough to do a system wide install).  I untarred it, moved it to /opt/eclipse and ran it. I then installed the Symfony 1.3 plugin, restarted, and Eclipse ran.  I don't know if it's the Fedora package or if it's something that got installed after Eclipse was installed.

**Comment by zulus** [comment]
Thanks, I'll try repeat this in next week.

**Comment by RangerGH** [comment]
I believe it's something in what Fedora does when they repackage Eclipse 
- or it may be another group that does it and not RedHat. On F23 I just 
installed the package they and so I did the same on F24. However, on a 
test VM I've been using the Oomph installer with bundles and pools and 
the Twig extension installed without issue.  I wanted to use whatever 
Fedora provided because I could just do dnf/yum update but Oomph is a 
much better way of installing, managing, and it has a lot of other 
really great features.

**Comment by zulus** [comment]
Everything working fine with Oxygen
