### ISSUE TITLE
Support import for specific PHPDoc tags (annotations)

### ISSUE THREAD

**Issue by raziel057** [pulse00/Symfony-2-Eclipse-Plugin#251]
I don't know if it's currently possible to implement the validators for custom PHPDoc tags. Currently with the last release of PDT, imports for Annotations (@....) are not taken into account and we have a validation warning: The import ...\...\... is never used.

![pdt_bug_use](https://cloud.githubusercontent.com/assets/652505/26827896/7863bb98-4abf-11e7-9be2-f98f6517fb2f.png)

I originally created a bug entry on PDT https://bugs.eclipse.org/bugs/show_bug.cgi?id=517368 but the validation taking care of annotation seems to be more related to the Symfony Eclipse plugin. The other validation error (for Trait) seems more related to PDT.

**Comment by zulus** [comment]
This should be resolved in Doctrine-Eclipse-Plugin. Eclipse bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=515930

**Comment by raziel057** [comment]
Thanks. Just to be sure, would it be working with other kind of annotation. 

For example in the following file with @Route, @Method, @Cache, @Security, ... ?
https://github.com/symfony/symfony-demo/blob/master/src/AppBundle/Controller/BlogController.php

**Comment by raziel057** [comment]
I confirm that it works like a charm. Thanks!
