### ISSUE TITLE
Issue with PHP PDT 5.0.1.201706221951

### ISSUE THREAD

**Issue by SOMERSOFTAndrewCrook** [pulse00/Symfony-2-Eclipse-Plugin#252]
Looks like they have removed the class org.eclipse.php.core.compiler.ast.visitor.PHPASTVisitor in this update.

https://github.com/pulse00/Symfony-2-Eclipse-Plugin/blob/master/com.dubture.symfony.core/src/com/dubture/symfony/core/codeassist/SymfonySelectionEngine.java

private static class AnnotationPathVisitor extends PHPASTVisitor

and it is causing problems with DLTK

Great Eclipse extension and will reinstall it once this has been fixed.

**Comment by hashkool** [comment]
@pulse00 / @SOMERSOFTAndrewCrook:  Can you add a _blocking label_? In the current situation the plugin is rendered unusable.

I wonder how much smart thinking was involved from the pdt devs to remove a public interface in a minor update (if I understand the situation correctly).

**Comment by zulus** [comment]
I release PDT 5.0 compatible versions

**Comment by hashkool** [comment]
@zulus Thanks a lot for putting your time into it! 

Does anyone know a temporary workaround? I did not make a backup of my workspace when upgrading from neon to oxygen, so going back to neon seems off the table for the moment.

**Comment by SOMERSOFTAndrewCrook** [comment]
The update is available from http://p2-dev.pdt-extensions.org/

**Comment by zulus** [comment]
@SOMERSOFTAndrewCrook It's in http://p2-dev.pdt-extensions.org/ and http://p2.pdt-extensions.org/
