### ISSUE TITLE
Annotation marked as never used

### ISSUE THREAD

**Issue by danjaredg** [pulse00/Symfony-2-Eclipse-Plugin#255]
If you use annotations with doctrine, routing and templates, the "use" statement is marked as never used

**Comment by zulus** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=515930

**Comment by danjaredg** [comment]
When the fix will be released?

**Comment by zulus** [comment]
I already release Oxygen.2 plugin compatible versions.
