### ISSUE TITLE
Cant install plugin from eclipse. timeout issues

### ISSUE THREAD

**Issue by savio-code** [pulse00/Symfony-2-Eclipse-Plugin#258]
Can install plugin from eclipse, page not found issue. 

"http://p2.pdt-extensions.org" returns a 404

![capture](https://user-images.githubusercontent.com/11610818/33554182-f70407c6-d8fb-11e7-9733-24b32a3109f6.PNG)

**Comment by zulus** [comment]
Which Eclipse version are you using?
