### ISSUE TITLE
Annotation still marked as never used (PDT 6, Photon)

### ISSUE THREAD

**Issue by Ezor** [pulse00/Symfony-2-Eclipse-Plugin#260]
Hi,

Using Eclipse Photon (4.8.0) with PDT 6.0 plugin, I still have imports marked as never used for annotations.

![annotations](https://user-images.githubusercontent.com/14620/45415009-f2c50c00-b67c-11e8-9f95-4abcf2355a12.jpg)

Is there a way to fix this without disabling the warnings in PHP preferences ?

**Comment by zulus** [comment]
make sure you are using latest sf/doctrine plugin. Next run project-> clean.

**Comment by zulus** [comment]
sf and doctrine plugin should be 1.5.0

**Comment by Ezor** [comment]
Well, Marketplace shows 1.4.2 but it's 1.5.0 that is installed.

Here is a screenshot of my config and as you can see I still have a warning (after a full clean/rebuild)

![annotations](https://user-images.githubusercontent.com/14620/45416613-995edc00-b680-11e8-88d7-33148f87efb1.jpg)

**Comment by zulus** [comment]
Is this symfony and/or doctrine support enabled for this project? Right click on project -> configure, add symfony support

**Comment by Ezor** [comment]
Yes the project already has symfony support. In the configure menu, I only have the "Remove symfony support"

**Comment by Ezor** [comment]
It's a Symfony 4.1.X project
