### ISSUE TITLE
Missing support for translation files

### ISSUE THREAD

**Issue by o-alquimista** [pulse00/Symfony-2-Eclipse-Plugin#265]
Support for `.xlf` files is missing. I have a couple of files such as `messages+intl-icu.pt.xlf` and they don't have a compatible editor after installing and configuring this plugin on my existing Symfony 4.4 project.

![Captura de tela de 2020-05-28 10-38-23](https://user-images.githubusercontent.com/25424263/83148468-60be9a80-a0cf-11ea-919f-c47e4a4f7aa2.png)

I've tried using the XML Editor and the XMLSchema Editor, but they refuse to work, telling me that the content is unsupported.

_________________________
Eclipse 2020.03 (4.15) installed with the Eclipse Installer from eclipse.org
PDT + Symfony plugin from Eclipse Marketplace
Fedora Workstation 32

**Comment by zulus** [comment]
I have to add mapping for xml files. In pdt we recently switched to wildwebdeveloper so fix will be for upcoming 2020-06 (is much faster than 2020-03 :P)

**Comment by o-alquimista** [comment]
To help anyone using 2020-03: the easy fix is to go to `Preferences/Content Types`, find `XML (Illformed)` and press `Add...` to add a new file association. Type `*.xlf`, then press Apply and Close. Your .xlf files will now open with the included XML Editor.

If not, just right-click one of the files and use the `Open With` menu option to set XML Editor as default.

**Comment by o-alquimista** [comment]
I'm running Eclipse 2020-06 and I can still reproduce this problem. My workaround (registering `*.xlf` for `XML (Illformed)`) is still useful.
