### ISSUE TITLE
Eclipse Installation needs some Bintray login

### ISSUE THREAD

**Issue by olimination** [pulse00/Symfony-2-Eclipse-Plugin#266]
I have tried to install the Symfony Eclipse plugin according to the docs here: https://pulse00.github.io/Symfony-2-Eclipse-Plugin/installation.html

But during the installation process Eclipse asks me to enter some dl.bintray.com login details. So I have created some Bintray account and entered my login details. But still it did not work, it did not accept my login details although I could login with these credentials on the Bintray website.

But actually the Eclipse user should not enter any Bintray login details or?

Thanks for support!

**Comment by zulus** [comment]
Fixed
