### ISSUE TITLE
Symfony Plugin 1.6.0 not available?

### ISSUE THREAD

**Issue by uw-richard** [pulse00/Symfony-2-Eclipse-Plugin#268]
I tried to install plugin to latest Eclipse 2021-06
Here is log
Similar problem is when I try to export plugin from existing install 

eclipse.buildId=4.20.0.I20210611-1600
java.version=11.0.11
java.vendor=Ubuntu
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.php.product
Command-line arguments:  -data file:/home/richard/eclipse-21-06-workspace/ -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.php.product

org.eclipse.epp.mpc.ui
Error
Mon Jul 05 08:51:14 CEST 2021
The following solutions are not available: Symfony Plugin 1.6.0 (id=com.dubture.symfony.feature.feature.group, org.dadacoalition.yedit.feature.feature.group, site=http://p2.pdt-extensions.org/)

**Comment by zulus** [comment]
Fixed
